.PHONY: build run test fmt vet lint cover build-all cross snapshot install-service stop reload e2e-handoff third-party-licenses

build:
	go build -o bin/portato ./cmd/portato

run:
	go run ./cmd/portato

test:
	go test ./...

# cover runs the tests with a coverage profile and prints the total.
cover:
	go test -coverprofile=cover.out ./...
	go tool cover -func=cover.out | tail -1

fmt:
	gofmt -w .

vet:
	go vet ./...

# lint runs golangci-lint with .golangci.yml: predeclared (no builtin
# shadowing, e.g. max/min/len) and gocyclo (cyclomatic complexity < 15),
# the local gate for the codefactor.io issue classes (Phase 33). Tests are
# excluded from gocyclo only.
# Requires golangci-lint v1.x: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
lint:
	golangci-lint run ./...

# build-all cross-compiles the binary for the MVP target matrix (SPEC §15).
# cross is a back-compat alias.
build-all:
	@for os in darwin linux; do \
	  for arch in amd64 arm64; do \
	    echo "==> $$os/$$arch"; \
	    GOOS=$$os GOARCH=$$arch go build -o bin/portato-$$os-$$arch ./cmd/portato || exit 1; \
	  done; \
	done

cross: build-all

# snapshot builds the full cross-platform release matrix locally via goreleaser
# (darwin/linux × amd64/arm64), writing archives + checksums.txt to dist/.
# No publish. Requires goreleaser: go install github.com/goreleaser/goreleaser/v2@latest
snapshot:
	goreleaser release --snapshot --clean

# install-service builds the local binary and registers autostart (Phase 6).
install-service: build
	./bin/portato install

# stop terminates the running daemon via the CLI (Phase 27).
stop:
	./bin/portato stop

# reload makes the running daemon re-read config.yaml via the CLI (Phase 28).
reload:
	./bin/portato reload

# e2e-handoff runs the Phase 16 black-box hand-off E2E: builds the real binary,
# spins up an in-process SSH server (internal/sshtest), and asserts the local
# port never refuses a connection across the standalone->daemon transition, plus
# the close+rebind fallback. Slower than unit tests, hence a separate target.
e2e-handoff:
	go test -tags e2e ./internal/tui/... -run TestHandoffE2E -v -count=1

# third-party-licenses regenerates the bundled THIRD_PARTY_LICENSES.txt: each
# runtime dependency's license text under a module-path header. Packed into
# release archives and the deb/rpm packages (Phase 32). Needs network for the
# first go-licenses install.
third-party-licenses:
	go install github.com/google/go-licenses@latest
	go-licenses save ./cmd/portato --save_path third_party --force
	@{ \
	  echo "Third-party licenses bundled with Portato"; \
	  echo "(permissive: MIT / Apache-2.0 / BSD). Each block below is one"; \
	  echo "dependency's license text, under its module path. Generated by"; \
	  echo "'make third-party-licenses' via github.com/google/go-licenses."; \
	  find third_party -type f | sort | while read f; do \
	    mod=$$(echo "$$f" | sed 's|^third_party/||'); \
	    printf '\n\n================================================================================\n%s\n================================================================================\n\n' "$$mod"; \
	    cat "$$f"; \
	  done; \
	} > THIRD_PARTY_LICENSES.txt
	@rm -rf third_party
